######################## default configuration ####################
baseURL = "http://radapp.dev/"
title = "Project Radius"
theme = "bigspring-light"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
disableFastRender = true
