# main menu

[[main]]
name = "Docs"
url = "https://docs.radapp.io"
weight = 1

[[main]]
name = "GitHub"
url = "https://github.com/radius-project"
weight = 2

[[main]]
name = "Blog"
url = "https://blog.radapp.io/posts"
weight = 3

[[main]]
name = "Community"
url = "https://github.com/radius-project/community"
weight = 4

[[main]]
name = "YouTube"
url = "https://www.youtube.com/@radapp_io"
weight = 5

# footer menu left
[[footer_left]]
name = "Concepts"
url = "https://docs.radapp.io/concepts/"

[[footer_left]]
name = "Getting Started"
url = "https://docs.radapp.io/getting-started/"

[[footer_left]]
name = "How-To guides"
url = "https://docs.radapp.io/guides/"

# footer menu middle
[[footer_middle]]
name = "GitHub"
url = "https://github.com/radius-project/community"

[[footer_middle]]
name = "Discord"
url = "https://aka.ms/Radius/Discord"

# footer menu right
[[footer_right]]
name = "Blogs"
url = "https://blog.radapp.io/posts"
