#################### default parameters ################################
logo = "images/logo.png"
logo_width = "200px"
favicon = "favicons/favicon.ico"
# OpenGraph / Twitter Card metadata
description = "Radius is a cloud-native, portable, application platform"
author = "Radius Project Leads"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

[variables]
primary_color = "#c43821"
light = "#f5f5f5"
primary_font = "Ubuntu"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Join our Discord"
link = "https://aka.ms/radius/discord"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################
[[social]]
title = "LinkedIn"
icon = "fab fa-linkedin-in" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/radius-project"

[[social]]
title = "X (Twitter)"
icon = "fab fa-x-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/radapp_io"

[[social]]
title = "Threads"
icon = "fab fa-threads" # themify icon : https://themify.me/themify-icons
link = "https://www.threads.net/@radapp_io"

[[social]]
title = "Discord"
icon = "fab fa-discord" # themify icon : https://themify.me/themify-icons
link = "https://aka.ms/radius/discord"

[[social]]
title = "GitHub"
icon = "fab fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/radius-project/radius"

[[social]]
title = "YouTube"
icon = "fab fa-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/@radapp_io"