# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Spellcheck

on:
  workflow_dispatch:
  push:
    branches:
      - v*.*
      - edge
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - v*.*
      - edge

permissions: {}

env:
  ACTION_LINK: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

concurrency:
  group: spellcheck-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@16d0338a5a3b5e3111a078029fb9a07a8125053d # 0.55.0
        with:
          config_path: .github/config/.pyspelling.yml

      - name: Post GitHub workflow output on failure
        if: failure()
        run: |
          {
            echo "## :x: Spellcheck Failed"
            echo "There are spelling errors in your PR. Visit [the workflow output](${{ env.ACTION_LINK }}) to see what words are failing."
            echo "### Adding new words"
            echo "If you are adding a new custom word refer to the [docs guide](https://docs.radapp.io/contributing/docs/#spelling)"
          } >> "${GITHUB_STEP_SUMMARY}"

      - name: Post GitHub workflow output on success
        run: |
          {
            echo "## :white_check_mark: Spellcheck Passed"
            echo "There are no spelling errors in your PR."
          } >> "${GITHUB_STEP_SUMMARY}"

      - name: Post GitHub comment on failure
        if: failure()
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        with:
          header: spellcheck
          recreate: true
          message: |
            ## :x: Spellcheck Failed
            There are spelling errors in your PR. Visit [the workflow output](${{ env.ACTION_LINK }}) to see what words are failing.
            ### Adding new words
            If you are adding a new custom word refer to the [docs guide](https://docs.radapp.io/contributing/docs/#spelling)

      - name: Clear GitHub comment on success
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        continue-on-error: true
        with:
          header: spellcheck
          delete: true
